Add configuration variables to jekyll static site
OpenGazettes/OpenGazettes pull request #11
Opened 2017-07-07 15:55 UTC by andela-wcyn

## What Does this PR do?
It replaces the hardcoded jurisdiction information with config variables and leaves the develop branch as a general branch that can be branched from when a new static site is created.

## Major changes made?
- A new branch has been created for the Kenya jurisdiction static site. This means that deploying the Kenya static site would require one to checkout into the kenya branch.
- Two new variables have been added to the env.example file:
`JURISDICTION`  and `JURISDICTION_CODE`. These variables are used in the `deploy.sh` file in order avoid manually editing the file when deploying the static site.
- The `_config.yml` file now has url and jurisdiction variables that are used in the html content. They have replaced the hard-coded values.
- The `build-index.py` file has also been edited to obtain jurisdiction data from the json file

2017-07-09 17:26 UTC, DavidLemayian commented on _includes/footer.html
> +        Gazettes from the <a href="https://dds.crl.edu/crldelivery/27040" target="_blank" rel="noopener">Center for Research Libraries: Global Resource Network</a>.
@andela-wcyn We should include the attribution in the config.yml as well for re-use.

2017-07-09 17:27 UTC, DavidLemayian commented on deploy.sh
> +for file in $DEPLOY_DIR/gazettes/NG/*.html; do
Should this also use `$JURISDICTION_CODE`?

2017-07-09 17:29 UTC, DavidLemayian requested changes
Just two slight changes but looks good overall.

2017-07-10 07:27 UTC, andela-wcyn commented on _includes/footer.html
> +        Gazettes from the <a href="https://dds.crl.edu/crldelivery/27040" target="_blank" rel="noopener">Center for Research Libraries: Global Resource Network</a>.
True. I'll do that

2017-07-10 07:27 UTC, andela-wcyn commented on deploy.sh
> +for file in $DEPLOY_DIR/gazettes/NG/*.html; do
Yea, I missed that one

2017-07-10 07:43 UTC, andela-wcyn commented
@DavidLemayian made the requested changes

2017-07-10 12:46 UTC, DavidLemayian approved these changes

2017-07-10 12:46 UTC, merged